### PR TITLE
Sending files to oneDrive 

### PR DESCRIPTION
**Pull request by brenoaraujolima**
Sending files to one drive.

### CODE REVIEW

**Review by jeffque — CHANGES_REQUESTED** [review]
I found this approach to be invalid.

Fetch config, call the specified drive, validate who is calling and save metadata, that's everything the API needs to know I think. But no details on the "call one drive" or "save to the disk".

Also, remove from `.env` stuff tenant specific

**Comment by brenoaraujolima** [comment]
> I found this approach to be invalid.
> 
> Fetch config, call the specified drive, validate who is calling and save metadata, that's everything the API needs to know I think. But no details on the "call one drive" or "save to the disk".
> 
> Also, remove from `.env` stuff tenant specific

Working on it

**Comment by jeffque** [comment]
@brenoaraujolima , notice that the issue #1 already has the driver cited. In issue #2 it was the intention that the "save to filesystem" was done by a driver way, the first driver.

The #8 (which is somewhat equivalent to upload to one drive) assumes that there already is a driver structure, just plug in details for uploading to s3. You can rewrite the idea behind PR #16 using the driver idea. Once this is done, the driver shall be a little more than one a handful of public functions, there would be no need to need anything in the `/api/` folder

**Comment by brenoaraujolima** [comment]
> @brenoaraujolima , notice that the issue #1 already has the driver cited. In issue #2 it was the intention that the "save to filesystem" was done by a driver way, the first driver.
> 
> The #8 (which is somewhat equivalent to upload to one drive) assumes that there already is a driver structure, just plug in details for uploading to s3. You can rewrite the idea behind PR #16 using the driver idea. Once this is done, the driver shall be a little more than one a handful of public functions, there would be no need to need anything in the `/api/` folder

I'm closing this PR. Trying to do it in #36 . Could you check if that approach is now valid ?

**Pull request closed without merging**
